# Used as inspiration: https://github.com/mvdan/github-actions-golang

name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install go
      uses: actions/setup-go@master
    
    - name: install xcaddy
      run: |
        tag_name=`curl -s https://api.github.com/repos/caddyserver/xcaddy/releases | grep 'tag_name' | sed -n '1p' | cut -d\" -f4 |sed 's/^v//'`
        curl -L https://github.com/caddyserver/xcaddy/releases/download/v${tag_name}/xcaddy_${tag_name}_linux_amd64.tar.gz |tar zvxf -
        chmod +x ./xcaddy

    - name: build caddy
      run: |
        export GOARCH=amd64
        export GOOS=linux
        ./xcaddy build \
          --with github.com/mholt/caddy-webdav

    - name: upload
      uses: actions/upload-artifact@master
      with:
        name: caddy-linux-amd64
        path: ./caddy
